dim: Fix create-branch dry run
Using --dry-run for git push on a non-existant branch (since the command
above doesn't actually create the branch) fails with:

error: src refspec topic/dim_test does not match any.
error: failed to push some refs to <remote>

So instead of using --dry-run for git push, just echo the command.

Changes in v2:
- Added comment (Daniel)

Reviewed-by: Daniel Vetter <daniel.vetter@ffwll.ch>
Signed-off-by: Sean Paul <seanpaul@chromium.org>
Signed-off-by: Jani Nikula <jani.nikula@intel.com>